# Generated by Django 5.2.8 on 2025-11-11 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adm',
            fields=[
                ('id_administracao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('idade', models.PositiveIntegerField(verbose_name='Idade (anos)')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=20, verbose_name='Sexo/Gênero')),
                ('estadosCivis', models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)/ União estável', 'Casado(a)/ União estável'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a)/ Separado(a)', 'Divorciado(a)/ Separado(a)')], max_length=50, verbose_name='Estado Civil')),
                ('escolaridade', models.CharField(choices=[('Nenhuma escolaridade formal', 'Nenhuma escolaridade formal'), ('Ensino fundamental incompleto', 'Ensino fundamental incompleto'), ('Ensino fundamental completo', 'Ensino Fundamental completo'), ('Ensino médio incompleto', 'Ensino médio incompleto'), ('Ensino médio completo', 'Ensino médio completo'), ('Ensino superior incompleto', 'Ensino superior incompleto'), ('Ensino superior completo', 'Ensino superior completo'), ('Pós-graduação', 'Pós-graduação')], max_length=70, verbose_name='Escolaridade')),
                ('moradias', models.CharField(choices=[('Mora sozinho(a)', 'Mora sozinho(a)'), ('Mora com cônjuge/companheiro(a)', 'Mora com cônjugue/companheiro(a)'), ('Mora com filhos', 'Mora com filhos'), ('Outro arranjo', 'Outro arranjo'), ('Mora em instituição (asilo, casa de repouso, ILPI)', 'Mora em instituição (asilo, casa de repouso, ILPI)')], max_length=80, verbose_name='Situação de Moradia')),
                ('residencias', models.CharField(choices=[('Zona urbana', 'Zona urbana'), ('Zona rural', 'Zona rural'), ('Zona periurbana (transição)', 'Zona periurbana (transição)')], max_length=60, verbose_name='Área de Residência')),
                ('ocupacoes', models.CharField(choices=[('Aposentado(a)', 'Aposentado(a)'), ('Trabalhador(a) ativo(a)', 'Trabalhador(a) ativo(a)'), ('Desempregado(a)', 'Desempregado(a)'), ('Trabalho voluntário', 'Trabalho voluntário'), ('Outro', 'Outro')], max_length=50, verbose_name='Situação Ocupacional')),
                ('rendaMensal', models.IntegerField(verbose_name='Renda Mensal (em salários mínimos)')),
                ('fontesRenda', models.CharField(choices=[('Aposentadoria/pensão', 'Aposentadoria/pensão'), ('Trabalho remunerado', 'Trabalho remunerado'), ('Apoio familiar', 'Apoio familiar'), ('Benefícios sociais', 'Benefícios sociais'), ('Outro', 'Outro')], max_length=255, verbose_name='Fonte de Renda')),
                ('planosSaude', models.CharField(choices=[('Apenas sistema público (SUS)', 'Apenas sistema público (SUS)'), ('Apenas plano privado', 'Apenas plano privado'), ('Sistema público + plano privado', 'Sistema público + plano privado'), ('Nenhum', 'Nenhum')], max_length=255, verbose_name='Plano de Saúde')),
                ('condicoesSaude', models.CharField(choices=[('Muito boa', 'Muito boa'), ('Boa', 'Boa'), ('Regular', 'Regular'), ('Ruim', 'Ruim'), ('Muito ruim', 'Muito ruim')], max_length=20, verbose_name='Condição de Saúde Autopercebida')),
                ('doencasCronicas', models.JSONField(default=list, verbose_name='Histórico de Doenças')),
                ('outraDoencaCronica', models.CharField(blank=True, max_length=100, null=True)),
                ('internacoes', models.CharField(choices=[('Sim, uma vez', 'Sim, uma vez'), ('Sim, duas ou mais vezes', 'Sim, duas ou mais vezes'), ('Não', 'Não')], max_length=50, verbose_name='Internações hospitalares (último ano)')),
                ('vacinacao', models.JSONField(default=list, verbose_name='Vacinação (últimos 12 meses)')),
                ('autocuidado', models.JSONField(default=list, verbose_name='Atividades de Autocuidado')),
                ('atividadesDomesticas', models.JSONField(default=list, verbose_name='Atividades Domésticas')),
                ('atividadesSociaisLazer', models.JSONField(default=list, verbose_name='Atividades Sociais e Lazer')),
                ('mobilidade', models.JSONField(default=list, verbose_name='Mobilidade')),
                ('funcoesCognitivas', models.JSONField(default=list, verbose_name='Funções Cognitivas')),
                ('atividadesSociais', models.JSONField(default=list, verbose_name='Atividades Sociais de Entretenimento')),
                ('atividadesLazer', models.JSONField(default=list, verbose_name='Atividades de Lazer')),
                ('atividadesCulturais', models.JSONField(default=list, verbose_name='Atividades Culturais')),
                ('atividadesFisicasRecreativas', models.JSONField(default=list, verbose_name='Atividades Físicas Recreativas')),
                ('atividadesFamiliares', models.JSONField(default=list, verbose_name='Atividades Familiares')),
                ('atividadesVoluntariado', models.JSONField(default=list, verbose_name='Atividades Voluntárias')),
            ],
            options={
                'verbose_name': 'Questionário Completo',
                'db_table': 'questionario',
            },
        ),
    ]
