# Generated by Django 5.2.7 on 2025-11-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_neuropsic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='user',
            name='senha',
        ),
    ]
