# Generated by Django 5.2.8 on 2025-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_neuropsic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='desprescricaoMedicamentos',
            field=models.CharField(choices=[('Menos de 6 meses', 'Menos de 6 meses'), ('Entre 6 meses e 1 ano', 'Entre 6 meses e 1 ano'), ('Mais de 1 ano', 'Mais de 1 ano'), ('Não sei', 'Não sei'), ('Não', 'Não')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='doencasCronicas',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Histórico de Doenças'),
        ),
        migrations.AlterField(
            model_name='user',
            name='revisaoMedicamentos',
            field=models.CharField(choices=[('Menos de 6 meses', 'Menos de 6 meses'), ('Entre 6 meses e 1 ano', 'Entre 6 meses e 1 ano'), ('Mais de 1 ano', 'Mais de 1 ano'), ('Não sei', 'Não sei'), ('Não', 'Não')], max_length=80),
        ),
    ]
