# Generated by Django 5.2.8 on 2025-11-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_neuropsic', '0002_alter_user_desprescricaomedicamentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
