# Generated by Django 5.2.8 on 2025-11-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_neuropsic', '0003_rename_hist_alc_user_alcool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fontesRenda',
            field=models.CharField(choices=[('Aposentadoria/pensão', 'Aposentadoria/pensão'), ('Trabalho remunerado', 'Trabalho remunerado'), ('Apoio familiar', 'Apoio familiar'), ('Benefícios sociais (ex.: Programas governamentais como Bolsa Família ou equivalente)', 'Benefícios sociais (ex.: Programas governamentais como Bolsa Família ou equivalente)'), ('Outro', 'Outro')], max_length=255, verbose_name='Fonte de Renda'),
        ),
        migrations.AlterField(
            model_name='user',
            name='planosSaude',
            field=models.CharField(choices=[('Apenas sistema público (SUS)', 'Apenas sistema público (SUS)'), ('Apenas plano privado', 'Apenas plano privado'), ('Sistema público + plano privado', 'Sistema público + plano privado'), ('Nenhum', 'Nenhum')], max_length=255, verbose_name='Plano de Saúde'),
        ),
    ]
